/**
 * PRD Synthesizer
 *
 * Combines all agent outputs into a final PRD Markdown document.
 * This is the final step that produces the downloadable PRD file.
 */

import {
  TechnicalPipelineResult,
  VisualPipelineResult,
  DetailLevel,
  ProductIdentity,
  InferenceConfidence,
  CoverageGap,
  CoverageGapsAnalysis,
  CONFIDENCE_THRESHOLDS,
} from '../core/technical-agent.types';

/**
 * Synthesize final PRD markdown from all agent outputs
 */
export function synthesizePRD(
  technicalResult: TechnicalPipelineResult,
  visualResult: VisualPipelineResult,
  detailLevel: DetailLevel
): string {
  const now = new Date().toISOString();
  const sourceUrl = visualResult.metadata.sourceUrl || 'Unknown';

  // Extract validation scores
  const validationScores = extractValidationScores(technicalResult.validationResult);
  const qaIterations = technicalResult.metadata.qaIterations;

  // Build PRD sections
  const sections: string[] = [];

  // Header
  sections.push(`# Product Requirements Document (PRD)

**Source URL:** ${sourceUrl}
**Generated:** ${now}
**Pipeline:** Visual + Technical
**Detail Level:** ${detailLevel.charAt(0).toUpperCase() + detailLevel.slice(1)}

---
`);

  // 1. Product Vision (NEW - from Identity Agent)
  sections.push(buildProductVisionSection(technicalResult.identity, technicalResult.identityConfidence));

  // 2. Visual Identity
  sections.push(buildVisualIdentitySection(visualResult));

  // 3. Product Requirements & User Stories
  sections.push(buildUserStoriesSection(technicalResult.userStories));

  // 4. Roadmap & Phasing (NEW)
  sections.push(buildRoadmapSection(technicalResult.userStories));

  // 5. Database Schema
  sections.push(buildDatabaseSection(technicalResult.databaseSchema));

  // 6. API Documentation
  sections.push(buildAPISection(technicalResult.backendArchitecture));

  // 7. Testing Strategy
  sections.push(buildTestingSection(technicalResult.testingStrategy));

  // 8. DevOps Configuration
  sections.push(buildDevOpsSection(technicalResult.devopsConfig));

  // 9. Tech Stack Summary
  sections.push(buildTechStackSection());

  // 10. Confidence Analysis
  sections.push(buildConfidenceSection(technicalResult.confidence));

  // 11. Validation Report
  sections.push(buildValidationReportSection(validationScores, qaIterations));

  // 12. Coverage Gaps (from per-inference confidence + skeptic review)
  const coverageGaps = generateCoverageGaps(technicalResult);
  sections.push(buildCoverageGapsSection(coverageGaps));

  // Footer
  sections.push(`
---

*Generated by VibeSquare V2.5 Technical Architecture Pipeline*
*Total Processing Time: ${technicalResult.metadata.processingTimeMs}ms*
*Agents Used: ${technicalResult.metadata.agentsUsed.join(', ')}*
`);

  return sections.join('\n');
}

/**
 * Build Product Vision section (from Identity Agent)
 */
function buildProductVisionSection(identity: ProductIdentity | undefined, confidence?: number): string {
  if (!identity) {
    return `## 1. Product Vision

> Product identity not generated.

---
`;
  }

  const { vision, problemStatement, valueProposition, aiCoderContext } = identity;

  return `## 1. Product Vision

${confidence ? `> **Analysis Confidence:** ${confidence}%` : ''}

### 1.1 Vision Statement

${vision.statement}

**Future State:** ${vision.futureState}

**User Transformation:** ${vision.transformation}

${vision.timeframe ? `**Timeframe:** ${vision.timeframe}` : ''}

### 1.2 Problem Statement

**Core Problem:** ${problemStatement.coreProblem}

**Affected Segments:**
${problemStatement.affectedSegments.length > 0
    ? problemStatement.affectedSegments
        .map((seg) => `- **${seg.name}**${seg.size ? ` (${seg.size})` : ''} - Pain Level: ${'🔴'.repeat(Math.min(Math.ceil(seg.painLevel / 2), 5))} (${seg.painLevel}/10)`)
        .join('\n')
    : '- Not specified'}

**Cost of Inaction:** ${problemStatement.costOfInaction}

${problemStatement.existingSolutions ? `**Existing Solutions:** ${problemStatement.existingSolutions}` : ''}

### 1.3 Value Proposition

**Unique Value:** ${valueProposition.uniqueValue}

**Target Audience:** ${valueProposition.targetAudience}

${valueProposition.competitiveAdvantage ? `**Competitive Advantage:** ${valueProposition.competitiveAdvantage}` : ''}

**Key Benefits:**
${valueProposition.keyBenefits.length > 0
    ? valueProposition.keyBenefits.map((b) => `- **${b.name}:** ${b.impact}`).join('\n')
    : '- Not specified'}

### 1.4 AI Coder Context

> This section helps AI coding assistants (Claude, Cursor, Copilot) understand the product quickly.

**Product Summary:**
${aiCoderContext.productSummary}

**Technical Spirit:** ${formatTechnicalSpirit(aiCoderContext.technicalSpirit)}

**Core Domain Entities:**
${aiCoderContext.coreEntities.length > 0 ? aiCoderContext.coreEntities.map((e) => `- \`${e}\``).join('\n') : '- Not specified'}

**Critical User Flows:**
${aiCoderContext.criticalFlows.length > 0 ? aiCoderContext.criticalFlows.map((f, i) => `${i + 1}. ${f}`).join('\n') : '- Not specified'}

${aiCoderContext.constraints.length > 0
    ? `**Constraints:**
${aiCoderContext.constraints.map((c) => `- ⚠️ ${c}`).join('\n')}`
    : ''}

---
`;
}

/**
 * Format technical spirit for display
 */
function formatTechnicalSpirit(spirit: string): string {
  const spiritMap: Record<string, string> = {
    modern: '🚀 Modern (Latest tech, cutting-edge patterns)',
    startup: '⚡ Startup (Fast iteration, MVP-focused)',
    enterprise: '🏢 Enterprise (Stable, well-documented, scalable)',
    legacy: '🔧 Legacy (Compatibility-focused, gradual migration)',
  };
  return spiritMap[spirit] || spirit;
}

/**
 * Build Visual Identity section
 */
function buildVisualIdentitySection(visual: VisualPipelineResult): string {
  const colors = visual.designSystem?.colors || {};
  const fonts = visual.designSystem?.fonts || {};
  const tone = visual.designSystem?.visualTone || 'modern';

  return `## 2. Visual Identity

### 2.1 Color Palette
| Role | Color |
|------|-------|
| Primary | ${colors.primary || '#2563EB'} |
| Secondary | ${colors.secondary || '#64748B'} |
| Accent | ${colors.accent || '#DC2626'} |
| Background | ${colors.background || '#FFFFFF'} |
| Text | ${colors.text || '#1F2937'} |

### 2.2 Typography
- **Headings:** ${fonts.heading || 'Inter'}
- **Body:** ${fonts.body || 'System UI'}

### 2.3 Visual Tone
${tone}

### 2.4 Layout Summary
${visual.layoutAnalysis?.layoutPattern || 'Standard responsive layout'}

### 2.5 Components Detected
${visual.componentIdentification?.components?.map((c) => `- ${c.type}: ${c.count} instance(s)`).join('\n') || '- Standard UI components'}

### 2.6 UI/UX Implementation Prompt

\`\`\`
${visual.finalPrompt || 'Visual prompt not available.'}
\`\`\`

---
`;
}

/**
 * Build User Stories & Product Requirements section (8 sub-sections)
 */
function buildUserStoriesSection(userStoriesXml: string): string {
  if (!userStoriesXml) {
    return `## 3. Product Requirements & User Stories

> User stories not generated.

---
`;
  }

  const sections: string[] = [];

  // 2.1 Background/Overview
  sections.push(formatBackground(userStoriesXml));

  // 2.2 Problem Statement
  sections.push(formatProblemStatement(userStoriesXml));

  // 2.3 Goals & Non-Goals
  sections.push(formatGoalsAndNonGoals(userStoriesXml));

  // 2.4 User Personas
  sections.push(formatPersonas(userStoriesXml));

  // 2.5 Epic → Feature → Story Hierarchy
  sections.push(formatEpicFeatureStoryHierarchy(userStoriesXml));

  // 2.6 Functional Requirements Summary
  sections.push(formatFunctionalRequirementsSummary(userStoriesXml));

  // 2.7 Edge Cases Summary
  sections.push(formatEdgeCasesSummary(userStoriesXml));

  // 2.8 Acceptance Criteria Summary
  sections.push(formatAcceptanceCriteriaSummary(userStoriesXml));

  return `## 3. Product Requirements & User Stories

${sections.join('\n')}

---
`;
}

/**
 * Format Background/Overview subsection
 */
function formatBackground(xml: string): string {
  const backgroundMatch = xml.match(/<background>([\s\S]*?)<\/background>/);
  if (!backgroundMatch) {
    return `### 3.1 Background/Overview

> Background information not available.
`;
  }

  const description = extractTextContent(backgroundMatch[1], 'description') || 'Application overview not provided.';
  const isNewFeature = extractTextContent(backgroundMatch[1], 'isNewFeature') === 'true';
  const existingContext = extractTextContent(backgroundMatch[1], 'existingContext');

  return `### 3.1 Background/Overview

${description}

**Type:** ${isNewFeature ? 'Feature Addition' : 'Complete Product'}
${existingContext ? `**Existing Context:** ${existingContext}` : ''}
`;
}

/**
 * Format Problem Statement subsection
 */
function formatProblemStatement(xml: string): string {
  const problemMatch = xml.match(/<problemStatement>([\s\S]*?)<\/problemStatement>/);
  if (!problemMatch) {
    return `### 3.2 Problem Statement

> Problem statement not available.
`;
  }

  const problem = extractTextContent(problemMatch[1], 'problem') || 'Problem not specified.';
  const affectedUsers = extractListItems(problemMatch[1], 'user');
  const workarounds = extractListItems(problemMatch[1], 'workaround');
  const impact = extractTextContent(problemMatch[1], 'impactIfNotSolved') || 'Impact not specified.';

  return `### 3.2 Problem Statement

**Problem:** ${problem}

**Affected Users:**
${affectedUsers.length > 0 ? affectedUsers.map((u) => `- ${u}`).join('\n') : '- Users not specified'}

**Current Workarounds:**
${workarounds.length > 0 ? workarounds.map((w) => `- ${w}`).join('\n') : '- None identified'}

**Impact if Not Solved:** ${impact}
`;
}

/**
 * Format Goals & Non-Goals subsection
 */
function formatGoalsAndNonGoals(xml: string): string {
  const goalsMatch = xml.match(/<goalsAndNonGoals>([\s\S]*?)<\/goalsAndNonGoals>/);
  if (!goalsMatch) {
    return `### 3.3 Goals & Non-Goals

> Goals and non-goals not available.
`;
  }

  // Extract goals
  const goalMatches = goalsMatch[1].match(/<goal[^>]*>([\s\S]*?)<\/goal>/g) || [];
  const goals = goalMatches.map((g) => {
    const priority = g.match(/priority="([^"]+)"/)?.[1] || 'must_have';
    const description = extractTextContent(g, 'description') || 'Goal description';
    const metric = extractTextContent(g, 'metric');
    return { priority, description, metric };
  });

  // Extract non-goals
  const nonGoalMatches = goalsMatch[1].match(/<nonGoal[^>]*>([\s\S]*?)<\/nonGoal>/g) || [];
  const nonGoals = nonGoalMatches.map((ng) => {
    const description = extractTextContent(ng, 'description') || 'Non-goal description';
    const reason = extractTextContent(ng, 'reason') || 'Reason not specified';
    return { description, reason };
  });

  // Extract success metrics
  const metricsMatch = goalsMatch[1].match(/<successMetrics>([\s\S]*?)<\/successMetrics>/);
  const metricMatches = metricsMatch ? metricsMatch[1].match(/<metric[^>]*>([\s\S]*?)<\/metric>/g) || [] : [];
  const metrics = metricMatches.map((m) => {
    const name = extractTextContent(m, 'name') || 'Metric';
    const target = extractTextContent(m, 'target') || 'TBD';
    const method = extractTextContent(m, 'measurementMethod') || 'TBD';
    const baseline = extractTextContent(m, 'baseline') || 'N/A';
    return { name, target, method, baseline };
  });

  return `### 3.3 Goals & Non-Goals

#### Goals
${goals.length > 0
    ? goals.map((g, i) => `${i + 1}. **${g.description}** _(${formatPriority(g.priority)})_${g.metric ? `\n   - Metric: ${g.metric}` : ''}`).join('\n')
    : '- No goals specified'}

#### Non-Goals
${nonGoals.length > 0
    ? nonGoals.map((ng, i) => `${i + 1}. ${ng.description}\n   - _Reason: ${ng.reason}_`).join('\n')
    : '- No non-goals specified'}

#### Success Metrics
${metrics.length > 0
    ? `| Metric | Target | Measurement | Baseline |
|--------|--------|-------------|----------|
${metrics.map((m) => `| ${m.name} | ${m.target} | ${m.method} | ${m.baseline} |`).join('\n')}`
    : '- No success metrics defined'}
`;
}

/**
 * Format User Personas subsection
 */
function formatPersonas(xml: string): string {
  const personasMatch = xml.match(/<personas>([\s\S]*?)<\/personas>/);
  if (!personasMatch) {
    return `### 3.4 User Personas

> User personas not available.
`;
  }

  const personaMatches = personasMatch[1].match(/<persona[^>]*>([\s\S]*?)<\/persona>/g) || [];

  if (personaMatches.length === 0) {
    return `### 3.4 User Personas

> No personas defined.
`;
  }

  const personas = personaMatches.map((p) => {
    const name = extractTextContent(p, 'name') || 'Unknown';
    const role = extractTextContent(p, 'role') || 'User';
    const demographicsMatch = p.match(/<demographics>([\s\S]*?)<\/demographics>/);
    const age = demographicsMatch ? extractTextContent(demographicsMatch[1], 'age') : '';
    const location = demographicsMatch ? extractTextContent(demographicsMatch[1], 'location') : '';
    const expertise = demographicsMatch ? extractTextContent(demographicsMatch[1], 'technicalExpertise') || 'intermediate' : 'intermediate';
    const needs = extractListItems(p, 'need');
    const painPoints = extractListItems(p, 'painPoint');
    const quotation = extractTextContent(p, 'quotation');

    return `#### ${name}
**Role:** ${role}
**Demographics:** ${[age, location].filter(Boolean).join(', ')} _(${expertise} technical skill)_

**Needs:**
${needs.length > 0 ? needs.map((n) => `- ${n}`).join('\n') : '- Not specified'}

**Pain Points:**
${painPoints.length > 0 ? painPoints.map((pp) => `- ${pp}`).join('\n') : '- Not specified'}

${quotation ? `> "${quotation}"` : ''}
`;
  });

  return `### 3.4 User Personas

${personas.join('\n---\n\n')}
`;
}

/**
 * Format Epic → Feature → Story Hierarchy subsection
 */
function formatEpicFeatureStoryHierarchy(xml: string): string {
  const epicsMatch = xml.match(/<epics>([\s\S]*?)<\/epics>/);
  if (!epicsMatch) {
    return `### 3.5 Epic → Feature → Story Breakdown

> User stories hierarchy not available.
`;
  }

  const epicMatches = epicsMatch[1].match(/<epic[^>]*>([\s\S]*?)<\/epic>/g) || [];

  if (epicMatches.length === 0) {
    return `### 3.5 Epic → Feature → Story Breakdown

> No epics defined.
`;
  }

  const epics = epicMatches.map((epicXml) => {
    const epicId = epicXml.match(/id="([^"]+)"/)?.[1] || 'E0';
    const epicName = epicXml.match(/name="([^"]+)"/)?.[1] || 'Unnamed Epic';
    const epicPriority = epicXml.match(/priority="([^"]+)"/)?.[1] || 'high';
    const businessObjective = extractTextContent(epicXml, 'businessObjective') || '';
    const estimatedDuration = extractTextContent(epicXml, 'estimatedDuration');

    // Parse features
    const featuresMatch = epicXml.match(/<features>([\s\S]*?)<\/features>/);
    const featureMatches = featuresMatch ? featuresMatch[1].match(/<feature[^>]*>([\s\S]*?)<\/feature>/g) || [] : [];

    const features = featureMatches.map((featureXml) => {
      const featureId = featureXml.match(/id="([^"]+)"/)?.[1] || 'F0';
      const featureName = featureXml.match(/name="([^"]+)"/)?.[1] || 'Unnamed Feature';
      const complexity = featureXml.match(/estimatedComplexity="([^"]+)"/)?.[1] || 'medium';
      const businessValue = extractTextContent(featureXml, 'businessValue') || '';

      // Parse stories
      const storiesMatch = featureXml.match(/<stories>([\s\S]*?)<\/stories>/);
      const storyMatches = storiesMatch ? storiesMatch[1].match(/<story[^>]*>([\s\S]*?)<\/story>/g) || [] : [];

      const stories = storyMatches.map((storyXml) => {
        const storyId = storyXml.match(/id="([^"]+)"/)?.[1] || 'US-000';
        const title = extractTextContent(storyXml, 'title') || 'Untitled Story';
        const asA = extractTextContent(storyXml, 'asA') || 'user';
        const iWant = extractTextContent(storyXml, 'iWant') || '';
        const soThat = extractTextContent(storyXml, 'soThat') || '';
        const priority = storyXml.match(/priority="([^"]+)"/)?.[1] || 'medium';
        const effort = storyXml.match(/estimatedEffort="([^"]+)"/)?.[1] || 'medium';
        const relatedEntities = extractListItems(storyXml, 'relatedEntity') || extractListItems(storyXml, 'entity');
        const relatedEndpoints = extractListItems(storyXml, 'relatedEndpoint') || extractListItems(storyXml, 'endpoint');

        return { storyId, title, asA, iWant, soThat, priority, effort, relatedEntities, relatedEndpoints };
      });

      return { featureId, featureName, complexity, businessValue, stories };
    });

    return { epicId, epicName, epicPriority, businessObjective, estimatedDuration, features };
  });

  const output = epics.map((epic) => {
    const featuresOutput = epic.features.map((feature) => {
      const storiesOutput = feature.stories.map((story) => {
        return `###### ${story.storyId}: ${story.title}
**As a** ${story.asA}, **I want** ${story.iWant}, **so that** ${story.soThat}

| Priority | Effort | Related Entities | Related Endpoints |
|----------|--------|------------------|-------------------|
| ${formatPriority(story.priority)} | ${story.effort} | ${story.relatedEntities.join(', ') || 'N/A'} | ${story.relatedEndpoints.join(', ') || 'N/A'} |
`;
      }).join('\n');

      return `##### Feature: ${feature.featureName} _(Complexity: ${feature.complexity})_
**ID:** ${feature.featureId}
${feature.businessValue ? `**Business Value:** ${feature.businessValue}` : ''}

**User Stories:**
${storiesOutput || '> No stories defined'}
`;
    }).join('\n---\n\n');

    return `#### Epic: ${epic.epicName} _(${formatPriority(epic.epicPriority)})_
**ID:** ${epic.epicId}
**Business Objective:** ${epic.businessObjective || 'Not specified'}
${epic.estimatedDuration ? `**Estimated Duration:** ${epic.estimatedDuration}` : ''}

${featuresOutput || '> No features defined'}
`;
  }).join('\n\n---\n\n');

  return `### 3.5 Epic → Feature → Story Breakdown

${output}
`;
}

/**
 * Format Functional Requirements Summary subsection
 */
function formatFunctionalRequirementsSummary(xml: string): string {
  // Count total functional requirements
  const reqMatches = xml.match(/<requirement[^>]*>([\s\S]*?)<\/requirement>/g) || [];
  const totalReqs = reqMatches.length;

  if (totalReqs === 0) {
    return `### 3.6 Functional Requirements Summary

> No functional requirements defined.
`;
  }

  // Sample some requirements
  const sampleReqs = reqMatches.slice(0, 5).map((r) => {
    const id = r.match(/id="([^"]+)"/)?.[1] || 'FR-X';
    const description = extractTextContent(r, 'description') || 'Requirement';
    const given = extractTextContent(r, 'given') || '';
    const when = extractTextContent(r, 'when') || '';
    const then = extractTextContent(r, 'then') || '';
    return { id, description, given, when, then };
  });

  return `### 3.6 Functional Requirements Summary

**Total Requirements:** ${totalReqs}

#### Sample Requirements (Given/When/Then Format)

${sampleReqs.map((r) => `**${r.id}: ${r.description}**
- **Given:** ${r.given || 'N/A'}
- **When:** ${r.when || 'N/A'}
- **Then:** ${r.then || 'N/A'}
`).join('\n')}

${totalReqs > 5 ? `> _...and ${totalReqs - 5} more requirements_` : ''}
`;
}

/**
 * Format Edge Cases Summary subsection
 */
function formatEdgeCasesSummary(xml: string): string {
  const edgeCaseMatches = xml.match(/<edgeCase[^>]*>([\s\S]*?)<\/edgeCase>/g) || [];
  const totalEdgeCases = edgeCaseMatches.length;

  if (totalEdgeCases === 0) {
    return `### 3.7 Edge Cases Summary

> No edge cases defined.
`;
  }

  // Categorize by severity
  const critical = edgeCaseMatches.filter((ec) => ec.includes('severity="critical"')).length;
  const major = edgeCaseMatches.filter((ec) => ec.includes('severity="major"')).length;
  const minor = edgeCaseMatches.filter((ec) => ec.includes('severity="minor"')).length;

  // Sample some edge cases
  const sampleCases = edgeCaseMatches.slice(0, 5).map((ec) => {
    const severity = ec.match(/severity="([^"]+)"/)?.[1] || 'major';
    const scenario = extractTextContent(ec, 'scenario') || 'Edge case';
    const expected = extractTextContent(ec, 'expectedBehavior') || '';
    return { severity, scenario, expected };
  });

  return `### 3.7 Edge Cases Summary

**Total Edge Cases:** ${totalEdgeCases}

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${critical} |
| 🟠 Major | ${major} |
| 🟡 Minor | ${minor} |

#### Sample Edge Cases

${sampleCases.map((ec) => `- **[${ec.severity.toUpperCase()}]** ${ec.scenario}
  - _Expected: ${ec.expected || 'Not specified'}_
`).join('\n')}

${totalEdgeCases > 5 ? `> _...and ${totalEdgeCases - 5} more edge cases_` : ''}
`;
}

/**
 * Format Acceptance Criteria Summary subsection
 */
function formatAcceptanceCriteriaSummary(xml: string): string {
  const criteriaMatches = xml.match(/<criterion[^>]*>([\s\S]*?)<\/criterion>/g) || [];
  const totalCriteria = criteriaMatches.length;

  if (totalCriteria === 0) {
    return `### 3.8 Acceptance Criteria Summary

> No acceptance criteria defined.
`;
  }

  // Categorize by type
  const functional = criteriaMatches.filter((c) => c.includes('type="functional"')).length;
  const ui = criteriaMatches.filter((c) => c.includes('type="ui"')).length;
  const security = criteriaMatches.filter((c) => c.includes('type="security"')).length;
  const performance = criteriaMatches.filter((c) => c.includes('type="performance"')).length;
  const accessibility = criteriaMatches.filter((c) => c.includes('type="accessibility"')).length;

  return `### 3.8 Acceptance Criteria Summary

**Total Criteria:** ${totalCriteria}

| Type | Count |
|------|-------|
| Functional | ${functional} |
| UI | ${ui} |
| Security | ${security} |
| Performance | ${performance} |
| Accessibility | ${accessibility} |

> Detailed acceptance criteria are included within each user story above.
`;
}

// ============ User Stories Helper Functions ============

/**
 * Extract text content from XML tag
 */
function extractTextContent(xml: string, tagName: string): string | undefined {
  // Try CDATA first
  const cdataMatch = xml.match(new RegExp(`<${tagName}><!\\[CDATA\\[([\\s\\S]*?)\\]\\]></${tagName}>`));
  if (cdataMatch) return cdataMatch[1]?.trim();

  // Try regular content
  const match = xml.match(new RegExp(`<${tagName}>([^<]*)</${tagName}>`));
  return match?.[1]?.trim();
}

/**
 * Extract list items from XML
 */
function extractListItems(xml: string, itemTagName: string): string[] {
  const items: string[] = [];
  const regex = new RegExp(`<${itemTagName}[^>]*>([^<]*)</${itemTagName}>`, 'g');
  let match;

  while ((match = regex.exec(xml)) !== null) {
    const text = match[1]?.trim();
    if (text) {
      items.push(text);
    }
  }

  return items;
}

/**
 * Format priority for display
 */
function formatPriority(priority: string): string {
  const priorityMap: Record<string, string> = {
    critical: '🔴 Critical',
    must_have: '🔴 Must Have',
    high: '🟠 High',
    should_have: '🟠 Should Have',
    medium: '🟡 Medium',
    nice_to_have: '🟡 Nice to Have',
    low: '🟢 Low',
    later: '⚪ Later',
  };
  return priorityMap[priority.toLowerCase()] || priority;
}

/**
 * Build Roadmap & Phasing section
 */
function buildRoadmapSection(userStoriesXml: string): string {
  if (!userStoriesXml) {
    return `## 4. Roadmap & Phasing

> Roadmap not generated.

---
`;
  }

  // Parse stories with phase information
  const storyMatches = userStoriesXml.match(/<story[^>]*>([\s\S]*?)<\/story>/g) || [];

  const phaseGroups: Record<string, Array<{ id: string; title: string; priority: string; businessValue: string }>> = {
    mvp: [],
    v2: [],
    v3: [],
    future: [],
  };

  storyMatches.forEach((storyXml) => {
    const id = storyXml.match(/id="([^"]+)"/)?.[1] || 'US-XXX';
    const titleMatch = storyXml.match(/<title>([^<]*)<\/title>/);
    const title = titleMatch?.[1] || 'Untitled Story';
    const priority = storyXml.match(/priority="([^"]+)"/)?.[1] || 'medium';

    // Extract phase
    const phaseMatch = storyXml.match(/<phase>([^<]*)<\/phase>/);
    const phase = phaseMatch?.[1]?.toLowerCase() || 'mvp';

    // Extract business value (qualitative)
    const bvMatch = storyXml.match(/<businessValue>([\s\S]*?)<\/businessValue>/);
    const qualitativeValue = bvMatch
      ? (bvMatch[1].match(/<qualitativeValue>([^<]*)<\/qualitativeValue>/)?.[1] || 'Value not specified')
      : 'Value not specified';

    if (phaseGroups[phase]) {
      phaseGroups[phase].push({ id, title, priority, businessValue: qualitativeValue });
    } else {
      phaseGroups.mvp.push({ id, title, priority, businessValue: qualitativeValue });
    }
  });

  const totalStories = storyMatches.length;
  const mvpCount = phaseGroups.mvp.length;
  const v2Count = phaseGroups.v2.length;
  const v3Count = phaseGroups.v3.length;
  const futureCount = phaseGroups.future.length;

  return `## 4. Roadmap & Phasing

### 4.1 Release Overview

| Phase | Story Count | Percentage |
|-------|-------------|------------|
| 🚀 **MVP** | ${mvpCount} | ${totalStories > 0 ? Math.round((mvpCount / totalStories) * 100) : 0}% |
| 📈 **V2** | ${v2Count} | ${totalStories > 0 ? Math.round((v2Count / totalStories) * 100) : 0}% |
| ✨ **V3** | ${v3Count} | ${totalStories > 0 ? Math.round((v3Count / totalStories) * 100) : 0}% |
| 🔮 **Future** | ${futureCount} | ${totalStories > 0 ? Math.round((futureCount / totalStories) * 100) : 0}% |

### 4.2 MVP Phase (Must Ship)

${phaseGroups.mvp.length > 0
    ? phaseGroups.mvp.map((s) => `- **${s.id}:** ${s.title} _(${formatPriority(s.priority)})_
  - _Business Value: ${s.businessValue}_`).join('\n')
    : '> No MVP stories defined.'}

### 4.3 V2 Phase (Important Improvements)

${phaseGroups.v2.length > 0
    ? phaseGroups.v2.map((s) => `- **${s.id}:** ${s.title} _(${formatPriority(s.priority)})_`).join('\n')
    : '> No V2 stories defined.'}

### 4.4 V3 Phase (Nice to Have)

${phaseGroups.v3.length > 0
    ? phaseGroups.v3.map((s) => `- **${s.id}:** ${s.title}`).join('\n')
    : '> No V3 stories defined.'}

### 4.5 Future Phase (Backlog)

${phaseGroups.future.length > 0
    ? phaseGroups.future.map((s) => `- ${s.id}: ${s.title}`).join('\n')
    : '> No future stories defined.'}

---
`;
}

/**
 * Build Database Schema section
 */
function buildDatabaseSection(databaseXml: string): string {
  if (!databaseXml) {
    return `## 5. Database Schema

> Database schema not generated.

---
`;
  }

  return `## 5. Database Schema

### 5.1 Schema Definition (XML)

\`\`\`xml
${databaseXml}
\`\`\`

### 5.2 Entity Summary

${extractEntitySummary(databaseXml)}

### 5.3 Relationships

${extractRelationshipSummary(databaseXml)}

---
`;
}

/**
 * Build API Documentation section
 */
function buildAPISection(backendXml: string): string {
  if (!backendXml) {
    return `## 6. API Documentation

> API documentation not generated.

---
`;
  }

  return `## 6. API Documentation

### 6.1 Architecture (XML)

\`\`\`xml
${backendXml}
\`\`\`

### 6.2 Endpoint Summary

${extractEndpointSummary(backendXml)}

### 6.3 Authentication

${extractAuthSummary(backendXml)}

---
`;
}

/**
 * Build Testing section
 */
function buildTestingSection(testingXml: string): string {
  if (!testingXml) {
    return `## 7. Testing Strategy

> Testing strategy not generated.

---
`;
  }

  return `## 7. Testing Strategy

### 7.1 Testing Configuration (XML)

\`\`\`xml
${testingXml}
\`\`\`

### 7.2 Test Suites

${extractTestSuitesSummary(testingXml)}

---
`;
}

/**
 * Build DevOps section
 */
function buildDevOpsSection(devopsXml: string): string {
  if (!devopsXml) {
    return `## 8. DevOps Configuration

> DevOps configuration not generated.

---
`;
  }

  return `## 8. DevOps Configuration

### 8.1 DevOps Configuration (XML)

\`\`\`xml
${devopsXml}
\`\`\`

### 8.2 Services

${extractServicesSummary(devopsXml)}

### 8.3 Hosting Recommendations

${extractHostingSummary(devopsXml)}

### 8.4 Analytics & KPIs

> Critical for AI Vibe Coders to understand success metrics and tracking requirements.

${extractAnalyticsSummary(devopsXml)}

### 8.5 Observability & Monitoring

${extractObservabilitySummary(devopsXml)}

---
`;
}

/**
 * Extract Analytics summary from DevOps XML
 */
function extractAnalyticsSummary(xml: string): string {
  const analyticsMatch = xml.match(/<analytics>([\s\S]*?)<\/analytics>/);
  if (!analyticsMatch) {
    return '> Analytics not configured.';
  }

  const analyticsXml = analyticsMatch[1];
  const sections: string[] = [];

  // Extract KPIs
  const kpiMatches = analyticsXml.match(/<kpi\s+name="([^"]+)"\s+target="([^"]+)"\s+measurementMethod="([^"]+)"\s+frequency="([^"]+)"/g) || [];
  if (kpiMatches.length > 0) {
    sections.push(`#### Key Performance Indicators (KPIs)

| KPI | Target | Measurement | Frequency |
|-----|--------|-------------|-----------|
${kpiMatches.map((kpi) => {
  const name = kpi.match(/name="([^"]+)"/)?.[1] || '';
  const target = kpi.match(/target="([^"]+)"/)?.[1] || '';
  const method = kpi.match(/measurementMethod="([^"]+)"/)?.[1] || '';
  const freq = kpi.match(/frequency="([^"]+)"/)?.[1] || '';
  return `| ${name} | ${target} | ${method} | ${freq} |`;
}).join('\n')}`);
  }

  // Extract Events
  const eventMatches = analyticsXml.match(/<event\s+name="([^"]+)"\s+trigger="([^"]+)"\s+category="([^"]+)"/g) || [];
  if (eventMatches.length > 0) {
    sections.push(`#### Tracking Events

| Event | Trigger | Category |
|-------|---------|----------|
${eventMatches.map((event) => {
  const name = event.match(/name="([^"]+)"/)?.[1] || '';
  const trigger = event.match(/trigger="([^"]+)"/)?.[1] || '';
  const category = event.match(/category="([^"]+)"/)?.[1] || '';
  const categoryIcon = {
    user_action: '👤',
    business: '💰',
    system: '⚙️',
    error: '❌',
  }[category] || '📊';
  return `| ${name} | ${trigger} | ${categoryIcon} ${category} |`;
}).join('\n')}`);
  }

  // Extract Dashboards
  const dashboardMatches = analyticsXml.match(/<dashboard\s+name="([^"]+)"/g) || [];
  if (dashboardMatches.length > 0) {
    sections.push(`#### Recommended Dashboards

${dashboardMatches.map((d) => {
  const name = d.match(/name="([^"]+)"/)?.[1] || '';
  return `- **${name}**`;
}).join('\n')}`);
  }

  return sections.length > 0 ? sections.join('\n\n') : '> Analytics not configured.';
}

/**
 * Extract Observability summary from DevOps XML
 */
function extractObservabilitySummary(xml: string): string {
  const obsMatch = xml.match(/<observability>([\s\S]*?)<\/observability>/);
  if (!obsMatch) {
    return '> Observability not configured.';
  }

  const obsXml = obsMatch[1];
  const sections: string[] = [];

  // Logging
  const formatMatch = obsXml.match(/<format>([^<]+)<\/format>/);
  const levelsMatch = obsXml.match(/<levels>([^<]+)<\/levels>/);
  const retentionMatch = obsXml.match(/<retention>([^<]+)<\/retention>/);

  if (formatMatch || levelsMatch || retentionMatch) {
    sections.push(`#### Logging Configuration

- **Format:** ${formatMatch?.[1] || 'JSON'}
- **Levels:** ${levelsMatch?.[1] || 'info, warn, error'}
- **Retention:** ${retentionMatch?.[1] || '30 days'}`);
  }

  // SLIs
  const sliMatches = obsXml.match(/<sli\s+name="([^"]+)"\s+target="([^"]+)"/g) || [];
  if (sliMatches.length > 0) {
    sections.push(`#### Service Level Indicators (SLIs)

| SLI | Target |
|-----|--------|
${sliMatches.map((sli) => {
  const name = sli.match(/name="([^"]+)"/)?.[1] || '';
  const target = sli.match(/target="([^"]+)"/)?.[1] || '';
  return `| ${name} | ${target} |`;
}).join('\n')}`);
  }

  // Alerts
  const alertMatches = obsXml.match(/<alert\s+name="([^"]+)"\s+severity="([^"]+)"\s+condition="([^"]+)">([\s\S]*?)<\/alert>/g) || [];
  if (alertMatches.length > 0) {
    sections.push(`#### Alerting Rules

| Alert | Severity | Condition |
|-------|----------|-----------|
${alertMatches.map((alert) => {
  const name = alert.match(/name="([^"]+)"/)?.[1] || '';
  const severity = alert.match(/severity="([^"]+)"/)?.[1] || '';
  const condition = alert.match(/condition="([^"]+)"/)?.[1] || '';
  const severityIcon = {
    critical: '🔴',
    warning: '🟠',
    info: '🟢',
  }[severity] || '⚪';
  return `| ${name} | ${severityIcon} ${severity} | ${condition} |`;
}).join('\n')}`);
  }

  // Tracing
  const providerMatch = obsXml.match(/<tracing>[\s\S]*?<provider>([^<]+)<\/provider>/);
  const samplingMatch = obsXml.match(/<samplingRate>([^<]+)<\/samplingRate>/);
  if (providerMatch) {
    sections.push(`#### Distributed Tracing

- **Provider:** ${providerMatch[1]}
- **Sampling Rate:** ${samplingMatch?.[1] || '10%'}`);
  }

  return sections.length > 0 ? sections.join('\n\n') : '> Observability not configured.';
}

/**
 * Build Tech Stack section
 */
function buildTechStackSection(): string {
  return `## 9. Tech Stack Summary

| Layer | Technology |
|-------|------------|
| **Backend** | Node.js + Express |
| **Database** | PostgreSQL |
| **ORM** | Prisma |
| **Frontend** | React |
| **API** | REST + GraphQL |
| **Auth** | JWT |
| **Containerization** | Docker |
| **CI/CD** | GitHub Actions |

---
`;
}

/**
 * Build Confidence Analysis section
 */
function buildConfidenceSection(confidence?: {
  overallScore: number;
  agentScores: Record<string, number>;
  lowConfidenceAreas: string[];
  clarificationNeeded: boolean;
}): string {
  if (!confidence) {
    return `## 10. Confidence Analysis

> Confidence scoring not available for this analysis.

---
`;
  }

  const { overallScore, agentScores, lowConfidenceAreas, clarificationNeeded } = confidence;

  // Determine overall confidence level
  let confidenceLevel: string;
  let confidenceIcon: string;
  if (overallScore >= CONFIDENCE_THRESHOLDS.HIGH) {
    confidenceLevel = 'High';
    confidenceIcon = '🟢';
  } else if (overallScore >= CONFIDENCE_THRESHOLDS.REQUIRE_CLARIFICATION) {
    confidenceLevel = 'Medium';
    confidenceIcon = '🟡';
  } else {
    confidenceLevel = 'Low';
    confidenceIcon = '🔴';
  }

  // Build agent scores table
  const agentScoresTable = Object.entries(agentScores)
    .map(([agent, score]) => {
      const icon = score >= 80 ? '🟢' : score >= 70 ? '🟡' : '🔴';
      const agentName = agent.charAt(0).toUpperCase() + agent.slice(1);
      return `| ${agentName} | ${icon} ${score}% |`;
    })
    .join('\n');

  return `## 10. Confidence Analysis

> This section shows how confident the AI analysis is about each part of the PRD.

### 10.1 Overall Confidence

${confidenceIcon} **${overallScore}%** - ${confidenceLevel} Confidence

${clarificationNeeded ? `⚠️ **Clarification Recommended**: Some areas may benefit from additional context or user input.` : '✅ **Analysis Complete**: Confidence level is acceptable for implementation.'}

### 10.2 Agent Confidence Scores

| Agent | Score |
|-------|-------|
${agentScoresTable || '| N/A | N/A |'}

### 10.3 Low Confidence Areas

${lowConfidenceAreas.length > 0
    ? `The following areas had lower confidence and may need review:

${lowConfidenceAreas.map((area) => `- ⚠️ ${area}`).join('\n')}`
    : '✅ No significant low-confidence areas identified.'}

### 10.4 Confidence Thresholds

| Level | Threshold | Meaning |
|-------|-----------|---------|
| 🟢 High | ≥${CONFIDENCE_THRESHOLDS.HIGH}% | Clear inference from UI, high-quality output |
| 🟡 Medium | ≥${CONFIDENCE_THRESHOLDS.REQUIRE_CLARIFICATION}% | Reasonable inference, may benefit from review |
| 🔴 Low | <${CONFIDENCE_THRESHOLDS.REQUIRE_CLARIFICATION}% | Significant inference, recommend clarification |

---
`;
}

/**
 * Build Validation Report section
 */
function buildValidationReportSection(
  scores: { completeness: number; consistency: number; security: number; implementability: number; overall: number },
  qaIterations: number
): string {
  return `## 11. Validation Report

| Metric | Score |
|--------|-------|
| Completeness | ${scores.completeness}/100 |
| Consistency | ${scores.consistency}/100 |
| Security | ${scores.security}/100 |
| Implementability | ${scores.implementability}/100 |
| **Overall** | **${scores.overall}/100** |

- **QA Iterations:** ${qaIterations}
- **Approval Status:** ${scores.overall >= 70 ? '✅ Approved' : '⚠️ Needs Review'}
`;
}

// ============ Helper Functions ============

function extractValidationScores(validationXml: string): {
  completeness: number;
  consistency: number;
  security: number;
  implementability: number;
  overall: number;
} {
  const defaultScores = { completeness: 0, consistency: 0, security: 0, implementability: 0, overall: 0 };

  if (!validationXml) return defaultScores;

  const completenessMatch = validationXml.match(/<completeness\s+score="(\d+)"/);
  const consistencyMatch = validationXml.match(/<consistency\s+score="(\d+)"/);
  const securityMatch = validationXml.match(/<security\s+score="(\d+)"/);
  const implementabilityMatch = validationXml.match(/<implementability\s+score="(\d+)"/);
  const overallMatch = validationXml.match(/<overall\s+score="(\d+)"/);

  return {
    completeness: completenessMatch ? parseInt(completenessMatch[1], 10) : 0,
    consistency: consistencyMatch ? parseInt(consistencyMatch[1], 10) : 0,
    security: securityMatch ? parseInt(securityMatch[1], 10) : 0,
    implementability: implementabilityMatch ? parseInt(implementabilityMatch[1], 10) : 0,
    overall: overallMatch ? parseInt(overallMatch[1], 10) : 0,
  };
}

function extractEntitySummary(xml: string): string {
  const entities = xml.match(/<entity\s+name="([^"]+)"/g) || [];
  if (entities.length === 0) return 'No entities defined.';

  return entities
    .map((e) => {
      const name = e.match(/name="([^"]+)"/)?.[1] || 'Unknown';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractRelationshipSummary(xml: string): string {
  const relations = xml.match(/<relation[^>]+\/>/g) || [];
  if (relations.length === 0) return 'No relationships defined.';

  return relations
    .map((r) => {
      const from = r.match(/from="([^"]+)"/)?.[1] || '';
      const to = r.match(/to="([^"]+)"/)?.[1] || '';
      const type = r.match(/type="([^"]+)"/)?.[1] || '';
      return `- ${from} → ${to} (${type})`;
    })
    .join('\n');
}

function extractEndpointSummary(xml: string): string {
  const resources = xml.match(/<resource\s+name="([^"]+)"/g) || [];
  if (resources.length === 0) return 'No endpoints defined.';

  const endpoints = xml.match(/<endpoint[^>]+method="([^"]+)"[^>]+path="([^"]+)"/g) || [];

  return `| Method | Path |
|--------|------|
${endpoints
    .slice(0, 15)
    .map((e) => {
      const method = e.match(/method="([^"]+)"/)?.[1] || '';
      const path = e.match(/path="([^"]+)"/)?.[1] || '';
      return `| ${method} | ${path} |`;
    })
    .join('\n')}${endpoints.length > 15 ? `\n\n*...and ${endpoints.length - 15} more endpoints*` : ''}`;
}

function extractAuthSummary(xml: string): string {
  const strategy = xml.match(/<strategy>([^<]+)<\/strategy>/)?.[1] || 'JWT';
  const accessExpiry = xml.match(/<accessTokenExpiry>([^<]+)<\/accessTokenExpiry>/)?.[1] || '15m';
  const refreshExpiry = xml.match(/<refreshTokenExpiry>([^<]+)<\/refreshTokenExpiry>/)?.[1] || '7d';

  return `- **Strategy:** ${strategy}
- **Access Token Expiry:** ${accessExpiry}
- **Refresh Token Expiry:** ${refreshExpiry}`;
}

function extractTestSuitesSummary(xml: string): string {
  const suites = xml.match(/<suite\s+name="([^"]+)"/g) || [];
  const resourceSuites = xml.match(/<suite\s+resource="([^"]+)"/g) || [];

  const allSuites = [
    ...suites.map((s) => s.match(/name="([^"]+)"/)?.[1] || ''),
    ...resourceSuites.map((s) => `${s.match(/resource="([^"]+)"/)?.[1] || ''} API Tests`),
  ].filter(Boolean);

  if (allSuites.length === 0) return 'No test suites defined.';

  return allSuites.map((s) => `- ${s}`).join('\n');
}

function extractServicesSummary(xml: string): string {
  const services = xml.match(/<service\s+name="([^"]+)"/g) || [];
  if (services.length === 0) return 'No services defined.';

  return services
    .map((s) => {
      const name = s.match(/name="([^"]+)"/)?.[1] || '';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractHostingSummary(xml: string): string {
  const recommendations = xml.match(/<recommendation\s+provider="([^"]+)"[^>]*>/g) || [];
  if (recommendations.length === 0) return 'No hosting recommendations.';

  return recommendations
    .map((r) => {
      const provider = r.match(/provider="([^"]+)"/)?.[1] || '';
      return `- **${provider}**`;
    })
    .join('\n');
}

// ============ Coverage Gaps ============

/**
 * Generate coverage gaps from per-inference confidence data and skeptic review
 */
function generateCoverageGaps(result: TechnicalPipelineResult): CoverageGapsAnalysis {
  const gaps: CoverageGap[] = [];
  const allInferences = result.confidence?.inferences || [];

  // 1. Low-confidence inferences (< 0.5)
  const lowConfInferences = allInferences.filter((i) => i.confidence < 0.5);
  for (const inf of lowConfInferences) {
    gaps.push({
      area: inf.source,
      description: inf.inference,
      reason: `Low confidence (${(inf.confidence * 100).toFixed(0)}%) — may not match actual requirements`,
      category: 'low_confidence',
      suggestedAction: 'Verify with stakeholders or provide additional UI screenshots',
    });
  }

  // 2. Inferences flagged for human review (no evidence)
  const humanReviewInferences = allInferences.filter((i) => i.humanReviewNeeded);
  const noEvidenceInferences = humanReviewInferences.filter(
    (i) => i.evidence.length === 0 && i.confidence >= 0.5
  );
  for (const inf of noEvidenceInferences) {
    gaps.push({
      area: inf.source,
      description: inf.inference,
      reason: 'No visual evidence cited for this inference',
      category: 'no_evidence',
      suggestedAction: 'Confirm this requirement exists or remove from specification',
    });
  }

  // 3. Skeptic-challenged items (parse from skepticReview XML if present)
  const challengedItems: string[] = [];
  if (result.skepticReview) {
    const challengeRegex = /<inference>([\s\S]*?)<\/inference>/g;
    let match;
    while ((match = challengeRegex.exec(result.skepticReview)) !== null) {
      const inference = match[1].trim();
      if (inference) {
        challengedItems.push(inference);
        gaps.push({
          area: 'Skeptic Review',
          description: inference,
          reason: 'Challenged by Skeptic Agent as potentially unsupported',
          category: 'challenged',
          suggestedAction: 'Review evidence and confirm or revise this assumption',
        });
      }
    }
  }

  // 4. Standard business logic gaps (areas that UI analysis commonly misses)
  const standardGaps: Array<{ area: string; description: string }> = [
    { area: 'Pricing & Billing', description: 'Pricing rules, subscription tiers, payment processing logic' },
    { area: 'Notification System', description: 'Email/push notification triggers, templates, and delivery rules' },
    { area: 'Data Migration', description: 'Migration strategy from existing systems (if applicable)' },
    { area: 'Permission Matrix', description: 'Detailed role-permission mappings beyond basic RBAC' },
    { area: 'Rate Limits & Quotas', description: 'Per-user and per-tier rate limits for API endpoints' },
  ];

  for (const sg of standardGaps) {
    // Check if any inference covers this area
    const covered = allInferences.some(
      (i) => i.inference.toLowerCase().includes(sg.area.toLowerCase().split(' ')[0])
    );
    if (!covered) {
      gaps.push({
        area: sg.area,
        description: sg.description,
        reason: 'Not detected in visual analysis — requires explicit specification',
        category: 'business_logic',
        suggestedAction: 'Define requirements if applicable to your product',
      });
    }
  }

  return {
    gaps,
    humanReviewInferences,
    challengedItems,
    counts: {
      total: gaps.length,
      lowConfidence: lowConfInferences.length,
      noEvidence: noEvidenceInferences.length,
      challenged: challengedItems.length,
      businessLogic: gaps.filter((g) => g.category === 'business_logic').length,
    },
  };
}

/**
 * Build Coverage Gaps section for the PRD
 */
function buildCoverageGapsSection(analysis: CoverageGapsAnalysis): string {
  if (analysis.gaps.length === 0) {
    return `## 12. Coverage Gaps & Limitations

> No significant coverage gaps identified. All inferences have supporting evidence.

---
`;
  }

  const { counts } = analysis;

  // Build gap table
  const gapRows = analysis.gaps
    .slice(0, 20) // Limit to top 20
    .map((g) => {
      const icon = g.category === 'low_confidence' ? '🔴'
        : g.category === 'no_evidence' ? '🟡'
        : g.category === 'challenged' ? '⚠️'
        : '📋';
      return `| ${icon} ${g.category} | ${g.area} | ${g.description.substring(0, 80)} | ${g.suggestedAction.substring(0, 60)} |`;
    })
    .join('\n');

  return `## 12. Coverage Gaps & Limitations

> This section identifies areas where the AI analysis is uncertain, unsupported, or incomplete.
> These gaps should be reviewed by stakeholders before implementation.

### 12.1 Gap Summary

| Category | Count |
|----------|-------|
| 🔴 Low Confidence Inferences | ${counts.lowConfidence} |
| 🟡 No Visual Evidence | ${counts.noEvidence} |
| ⚠️ Challenged by Skeptic | ${counts.challenged} |
| 📋 Missing Business Logic | ${counts.businessLogic} |
| **Total** | **${counts.total}** |

### 12.2 Gap Details

| Type | Area | Description | Suggested Action |
|------|------|-------------|-----------------|
${gapRows}

### 12.3 What This Means

- **Low Confidence**: The AI inferred these items but isn't sure they're correct. Verify before implementing.
- **No Evidence**: These items were generated without direct visual support. They may be hallucinated.
- **Challenged**: The Skeptic Agent flagged these as potentially wrong or over-specified.
- **Business Logic**: Standard requirements that visual analysis can't detect. Define manually if needed.

---
`;
}

export default synthesizePRD;
