/**
 * PRD Synthesizer
 *
 * Combines all agent outputs into a final PRD Markdown document.
 * This is the final step that produces the downloadable PRD file.
 */

import {
  TechnicalPipelineResult,
  VisualPipelineResult,
  DetailLevel,
} from '../core/technical-agent.types';

/**
 * Synthesize final PRD markdown from all agent outputs
 */
export function synthesizePRD(
  technicalResult: TechnicalPipelineResult,
  visualResult: VisualPipelineResult,
  detailLevel: DetailLevel
): string {
  const now = new Date().toISOString();
  const sourceUrl = visualResult.metadata.sourceUrl || 'Unknown';

  // Extract validation scores
  const validationScores = extractValidationScores(technicalResult.validationResult);
  const qaIterations = technicalResult.metadata.qaIterations;

  // Build PRD sections
  const sections: string[] = [];

  // Header
  sections.push(`# Product Requirements Document (PRD)

**Source URL:** ${sourceUrl}
**Generated:** ${now}
**Pipeline:** Visual + Technical
**Detail Level:** ${detailLevel.charAt(0).toUpperCase() + detailLevel.slice(1)}

---
`);

  // 1. Visual Identity
  sections.push(buildVisualIdentitySection(visualResult));

  // 2. Database Schema
  sections.push(buildDatabaseSection(technicalResult.databaseSchema));

  // 3. API Documentation
  sections.push(buildAPISection(technicalResult.backendArchitecture));

  // 4. Security Recommendations
  sections.push(buildSecuritySection(technicalResult.securityRecommendations));

  // 5. Testing Strategy
  sections.push(buildTestingSection(technicalResult.testingStrategy));

  // 6. DevOps Configuration
  sections.push(buildDevOpsSection(technicalResult.devopsConfig));

  // 7. Tech Stack Summary
  sections.push(buildTechStackSection());

  // 8. Validation Report
  sections.push(buildValidationReportSection(validationScores, qaIterations));

  // Footer
  sections.push(`
---

*Generated by VibeSquare V2.5 Technical Architecture Pipeline*
*Total Processing Time: ${technicalResult.metadata.processingTimeMs}ms*
*Agents Used: ${technicalResult.metadata.agentsUsed.join(', ')}*
`);

  return sections.join('\n');
}

/**
 * Build Visual Identity section
 */
function buildVisualIdentitySection(visual: VisualPipelineResult): string {
  const colors = visual.designSystem?.colors || {};
  const fonts = visual.designSystem?.fonts || {};
  const tone = visual.designSystem?.visualTone || 'modern';

  return `## 1. Visual Identity

### 1.1 Color Palette
| Role | Color |
|------|-------|
| Primary | ${colors.primary || '#2563EB'} |
| Secondary | ${colors.secondary || '#64748B'} |
| Accent | ${colors.accent || '#DC2626'} |
| Background | ${colors.background || '#FFFFFF'} |
| Text | ${colors.text || '#1F2937'} |

### 1.2 Typography
- **Headings:** ${fonts.heading || 'Inter'}
- **Body:** ${fonts.body || 'System UI'}

### 1.3 Visual Tone
${tone}

### 1.4 Layout Summary
${visual.layoutAnalysis?.layoutPattern || 'Standard responsive layout'}

### 1.5 Components Detected
${visual.componentIdentification?.components?.map((c) => `- ${c.type}: ${c.count} instance(s)`).join('\n') || '- Standard UI components'}

---
`;
}

/**
 * Build Database Schema section
 */
function buildDatabaseSection(databaseXml: string): string {
  if (!databaseXml) {
    return `## 2. Database Schema

> Database schema not generated.

---
`;
  }

  return `## 2. Database Schema

### 2.1 Schema Definition (XML)

\`\`\`xml
${databaseXml}
\`\`\`

### 2.2 Entity Summary

${extractEntitySummary(databaseXml)}

### 2.3 Relationships

${extractRelationshipSummary(databaseXml)}

---
`;
}

/**
 * Build API Documentation section
 */
function buildAPISection(backendXml: string): string {
  if (!backendXml) {
    return `## 3. API Documentation

> API documentation not generated.

---
`;
  }

  return `## 3. API Documentation

### 3.1 Architecture (XML)

\`\`\`xml
${backendXml}
\`\`\`

### 3.2 Endpoint Summary

${extractEndpointSummary(backendXml)}

### 3.3 Authentication

${extractAuthSummary(backendXml)}

---
`;
}

/**
 * Build Security section
 */
function buildSecuritySection(securityXml: string): string {
  if (!securityXml) {
    return `## 4. Security Recommendations

> Security recommendations not generated.

---
`;
  }

  return `## 4. Security Recommendations

### 4.1 Security Configuration (XML)

\`\`\`xml
${securityXml}
\`\`\`

### 4.2 OWASP Coverage

${extractOwaspSummary(securityXml)}

### 4.3 Data Protection

${extractDataProtectionSummary(securityXml)}

---
`;
}

/**
 * Build Testing section
 */
function buildTestingSection(testingXml: string): string {
  if (!testingXml) {
    return `## 5. Testing Strategy

> Testing strategy not generated.

---
`;
  }

  return `## 5. Testing Strategy

### 5.1 Testing Configuration (XML)

\`\`\`xml
${testingXml}
\`\`\`

### 5.2 Test Suites

${extractTestSuitesSummary(testingXml)}

---
`;
}

/**
 * Build DevOps section
 */
function buildDevOpsSection(devopsXml: string): string {
  if (!devopsXml) {
    return `## 6. DevOps Configuration

> DevOps configuration not generated.

---
`;
  }

  return `## 6. DevOps Configuration

### 6.1 DevOps Configuration (XML)

\`\`\`xml
${devopsXml}
\`\`\`

### 6.2 Services

${extractServicesSummary(devopsXml)}

### 6.3 Hosting Recommendations

${extractHostingSummary(devopsXml)}

---
`;
}

/**
 * Build Tech Stack section
 */
function buildTechStackSection(): string {
  return `## 7. Tech Stack Summary

| Layer | Technology |
|-------|------------|
| **Backend** | Node.js + Express |
| **Database** | PostgreSQL |
| **ORM** | Prisma |
| **Frontend** | React |
| **API** | REST + GraphQL |
| **Auth** | JWT |
| **Containerization** | Docker |
| **CI/CD** | GitHub Actions |

---
`;
}

/**
 * Build Validation Report section
 */
function buildValidationReportSection(
  scores: { completeness: number; consistency: number; security: number; implementability: number; overall: number },
  qaIterations: number
): string {
  return `## 8. Validation Report

| Metric | Score |
|--------|-------|
| Completeness | ${scores.completeness}/100 |
| Consistency | ${scores.consistency}/100 |
| Security | ${scores.security}/100 |
| Implementability | ${scores.implementability}/100 |
| **Overall** | **${scores.overall}/100** |

- **QA Iterations:** ${qaIterations}
- **Approval Status:** ${scores.overall >= 70 ? '✅ Approved' : '⚠️ Needs Review'}
`;
}

// ============ Helper Functions ============

function extractValidationScores(validationXml: string): {
  completeness: number;
  consistency: number;
  security: number;
  implementability: number;
  overall: number;
} {
  const defaultScores = { completeness: 0, consistency: 0, security: 0, implementability: 0, overall: 0 };

  if (!validationXml) return defaultScores;

  const completenessMatch = validationXml.match(/<completeness\s+score="(\d+)"/);
  const consistencyMatch = validationXml.match(/<consistency\s+score="(\d+)"/);
  const securityMatch = validationXml.match(/<security\s+score="(\d+)"/);
  const implementabilityMatch = validationXml.match(/<implementability\s+score="(\d+)"/);
  const overallMatch = validationXml.match(/<overall\s+score="(\d+)"/);

  return {
    completeness: completenessMatch ? parseInt(completenessMatch[1], 10) : 0,
    consistency: consistencyMatch ? parseInt(consistencyMatch[1], 10) : 0,
    security: securityMatch ? parseInt(securityMatch[1], 10) : 0,
    implementability: implementabilityMatch ? parseInt(implementabilityMatch[1], 10) : 0,
    overall: overallMatch ? parseInt(overallMatch[1], 10) : 0,
  };
}

function extractEntitySummary(xml: string): string {
  const entities = xml.match(/<entity\s+name="([^"]+)"/g) || [];
  if (entities.length === 0) return 'No entities defined.';

  return entities
    .map((e) => {
      const name = e.match(/name="([^"]+)"/)?.[1] || 'Unknown';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractRelationshipSummary(xml: string): string {
  const relations = xml.match(/<relation[^>]+\/>/g) || [];
  if (relations.length === 0) return 'No relationships defined.';

  return relations
    .map((r) => {
      const from = r.match(/from="([^"]+)"/)?.[1] || '';
      const to = r.match(/to="([^"]+)"/)?.[1] || '';
      const type = r.match(/type="([^"]+)"/)?.[1] || '';
      return `- ${from} → ${to} (${type})`;
    })
    .join('\n');
}

function extractEndpointSummary(xml: string): string {
  const resources = xml.match(/<resource\s+name="([^"]+)"/g) || [];
  if (resources.length === 0) return 'No endpoints defined.';

  const endpoints = xml.match(/<endpoint[^>]+method="([^"]+)"[^>]+path="([^"]+)"/g) || [];

  return `| Method | Path |
|--------|------|
${endpoints
    .slice(0, 15)
    .map((e) => {
      const method = e.match(/method="([^"]+)"/)?.[1] || '';
      const path = e.match(/path="([^"]+)"/)?.[1] || '';
      return `| ${method} | ${path} |`;
    })
    .join('\n')}${endpoints.length > 15 ? `\n\n*...and ${endpoints.length - 15} more endpoints*` : ''}`;
}

function extractAuthSummary(xml: string): string {
  const strategy = xml.match(/<strategy>([^<]+)<\/strategy>/)?.[1] || 'JWT';
  const accessExpiry = xml.match(/<accessTokenExpiry>([^<]+)<\/accessTokenExpiry>/)?.[1] || '15m';
  const refreshExpiry = xml.match(/<refreshTokenExpiry>([^<]+)<\/refreshTokenExpiry>/)?.[1] || '7d';

  return `- **Strategy:** ${strategy}
- **Access Token Expiry:** ${accessExpiry}
- **Refresh Token Expiry:** ${refreshExpiry}`;
}

function extractOwaspSummary(xml: string): string {
  const risks = xml.match(/<risk\s+name="([^"]+)"/g) || [];
  if (risks.length === 0) return 'OWASP coverage not specified.';

  return risks
    .map((r) => {
      const name = r.match(/name="([^"]+)"/)?.[1] || '';
      return `- ✅ ${name}`;
    })
    .join('\n');
}

function extractDataProtectionSummary(xml: string): string {
  const atRest = xml.match(/atRest="([^"]+)"/)?.[1] || 'true';
  const inTransit = xml.match(/inTransit="([^"]+)"/)?.[1] || 'true';

  return `- **Encryption at Rest:** ${atRest === 'true' ? 'Yes' : 'No'}
- **Encryption in Transit:** ${inTransit === 'true' ? 'Yes (TLS)' : 'No'}`;
}

function extractTestSuitesSummary(xml: string): string {
  const suites = xml.match(/<suite\s+name="([^"]+)"/g) || [];
  const resourceSuites = xml.match(/<suite\s+resource="([^"]+)"/g) || [];

  const allSuites = [
    ...suites.map((s) => s.match(/name="([^"]+)"/)?.[1] || ''),
    ...resourceSuites.map((s) => `${s.match(/resource="([^"]+)"/)?.[1] || ''} API Tests`),
  ].filter(Boolean);

  if (allSuites.length === 0) return 'No test suites defined.';

  return allSuites.map((s) => `- ${s}`).join('\n');
}

function extractServicesSummary(xml: string): string {
  const services = xml.match(/<service\s+name="([^"]+)"/g) || [];
  if (services.length === 0) return 'No services defined.';

  return services
    .map((s) => {
      const name = s.match(/name="([^"]+)"/)?.[1] || '';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractHostingSummary(xml: string): string {
  const recommendations = xml.match(/<recommendation\s+provider="([^"]+)"[^>]*>/g) || [];
  if (recommendations.length === 0) return 'No hosting recommendations.';

  return recommendations
    .map((r) => {
      const provider = r.match(/provider="([^"]+)"/)?.[1] || '';
      return `- **${provider}**`;
    })
    .join('\n');
}

export default synthesizePRD;
