/**
 * PRD Synthesizer
 *
 * Combines all agent outputs into a final PRD Markdown document.
 * This is the final step that produces the downloadable PRD file.
 */

import {
  TechnicalPipelineResult,
  VisualPipelineResult,
  DetailLevel,
} from '../core/technical-agent.types';

/**
 * Synthesize final PRD markdown from all agent outputs
 */
export function synthesizePRD(
  technicalResult: TechnicalPipelineResult,
  visualResult: VisualPipelineResult,
  detailLevel: DetailLevel
): string {
  const now = new Date().toISOString();
  const sourceUrl = visualResult.metadata.sourceUrl || 'Unknown';

  // Extract validation scores
  const validationScores = extractValidationScores(technicalResult.validationResult);
  const qaIterations = technicalResult.metadata.qaIterations;

  // Build PRD sections
  const sections: string[] = [];

  // Header
  sections.push(`# Product Requirements Document (PRD)

**Source URL:** ${sourceUrl}
**Generated:** ${now}
**Pipeline:** Visual + Technical
**Detail Level:** ${detailLevel.charAt(0).toUpperCase() + detailLevel.slice(1)}

---
`);

  // 1. Visual Identity
  sections.push(buildVisualIdentitySection(visualResult));

  // 2. Product Requirements & User Stories (NEW)
  sections.push(buildUserStoriesSection(technicalResult.userStories));

  // 3. Database Schema (was 2)
  sections.push(buildDatabaseSection(technicalResult.databaseSchema));

  // 4. API Documentation (was 3)
  sections.push(buildAPISection(technicalResult.backendArchitecture));

  // 5. Security Recommendations (was 4)
  sections.push(buildSecuritySection(technicalResult.securityRecommendations));

  // 6. Testing Strategy (was 5)
  sections.push(buildTestingSection(technicalResult.testingStrategy));

  // 7. DevOps Configuration (was 6)
  sections.push(buildDevOpsSection(technicalResult.devopsConfig));

  // 8. Tech Stack Summary (was 7)
  sections.push(buildTechStackSection());

  // 9. Validation Report (was 8)
  sections.push(buildValidationReportSection(validationScores, qaIterations));

  // Footer
  sections.push(`
---

*Generated by VibeSquare V2.5 Technical Architecture Pipeline*
*Total Processing Time: ${technicalResult.metadata.processingTimeMs}ms*
*Agents Used: ${technicalResult.metadata.agentsUsed.join(', ')}*
`);

  return sections.join('\n');
}

/**
 * Build Visual Identity section
 */
function buildVisualIdentitySection(visual: VisualPipelineResult): string {
  const colors = visual.designSystem?.colors || {};
  const fonts = visual.designSystem?.fonts || {};
  const tone = visual.designSystem?.visualTone || 'modern';

  return `## 1. Visual Identity

### 1.1 Color Palette
| Role | Color |
|------|-------|
| Primary | ${colors.primary || '#2563EB'} |
| Secondary | ${colors.secondary || '#64748B'} |
| Accent | ${colors.accent || '#DC2626'} |
| Background | ${colors.background || '#FFFFFF'} |
| Text | ${colors.text || '#1F2937'} |

### 1.2 Typography
- **Headings:** ${fonts.heading || 'Inter'}
- **Body:** ${fonts.body || 'System UI'}

### 1.3 Visual Tone
${tone}

### 1.4 Layout Summary
${visual.layoutAnalysis?.layoutPattern || 'Standard responsive layout'}

### 1.5 Components Detected
${visual.componentIdentification?.components?.map((c) => `- ${c.type}: ${c.count} instance(s)`).join('\n') || '- Standard UI components'}

---
`;
}

/**
 * Build User Stories & Product Requirements section (8 sub-sections)
 */
function buildUserStoriesSection(userStoriesXml: string): string {
  if (!userStoriesXml) {
    return `## 2. Product Requirements & User Stories

> User stories not generated.

---
`;
  }

  const sections: string[] = [];

  // 2.1 Background/Overview
  sections.push(formatBackground(userStoriesXml));

  // 2.2 Problem Statement
  sections.push(formatProblemStatement(userStoriesXml));

  // 2.3 Goals & Non-Goals
  sections.push(formatGoalsAndNonGoals(userStoriesXml));

  // 2.4 User Personas
  sections.push(formatPersonas(userStoriesXml));

  // 2.5 Epic → Feature → Story Hierarchy
  sections.push(formatEpicFeatureStoryHierarchy(userStoriesXml));

  // 2.6 Functional Requirements Summary
  sections.push(formatFunctionalRequirementsSummary(userStoriesXml));

  // 2.7 Edge Cases Summary
  sections.push(formatEdgeCasesSummary(userStoriesXml));

  // 2.8 Acceptance Criteria Summary
  sections.push(formatAcceptanceCriteriaSummary(userStoriesXml));

  return `## 2. Product Requirements & User Stories

${sections.join('\n')}

---
`;
}

/**
 * Format Background/Overview subsection
 */
function formatBackground(xml: string): string {
  const backgroundMatch = xml.match(/<background>([\s\S]*?)<\/background>/);
  if (!backgroundMatch) {
    return `### 2.1 Background/Overview

> Background information not available.
`;
  }

  const description = extractTextContent(backgroundMatch[1], 'description') || 'Application overview not provided.';
  const isNewFeature = extractTextContent(backgroundMatch[1], 'isNewFeature') === 'true';
  const existingContext = extractTextContent(backgroundMatch[1], 'existingContext');

  return `### 2.1 Background/Overview

${description}

**Type:** ${isNewFeature ? 'Feature Addition' : 'Complete Product'}
${existingContext ? `**Existing Context:** ${existingContext}` : ''}
`;
}

/**
 * Format Problem Statement subsection
 */
function formatProblemStatement(xml: string): string {
  const problemMatch = xml.match(/<problemStatement>([\s\S]*?)<\/problemStatement>/);
  if (!problemMatch) {
    return `### 2.2 Problem Statement

> Problem statement not available.
`;
  }

  const problem = extractTextContent(problemMatch[1], 'problem') || 'Problem not specified.';
  const affectedUsers = extractListItems(problemMatch[1], 'user');
  const workarounds = extractListItems(problemMatch[1], 'workaround');
  const impact = extractTextContent(problemMatch[1], 'impactIfNotSolved') || 'Impact not specified.';

  return `### 2.2 Problem Statement

**Problem:** ${problem}

**Affected Users:**
${affectedUsers.length > 0 ? affectedUsers.map((u) => `- ${u}`).join('\n') : '- Users not specified'}

**Current Workarounds:**
${workarounds.length > 0 ? workarounds.map((w) => `- ${w}`).join('\n') : '- None identified'}

**Impact if Not Solved:** ${impact}
`;
}

/**
 * Format Goals & Non-Goals subsection
 */
function formatGoalsAndNonGoals(xml: string): string {
  const goalsMatch = xml.match(/<goalsAndNonGoals>([\s\S]*?)<\/goalsAndNonGoals>/);
  if (!goalsMatch) {
    return `### 2.3 Goals & Non-Goals

> Goals and non-goals not available.
`;
  }

  // Extract goals
  const goalMatches = goalsMatch[1].match(/<goal[^>]*>([\s\S]*?)<\/goal>/g) || [];
  const goals = goalMatches.map((g) => {
    const priority = g.match(/priority="([^"]+)"/)?.[1] || 'must_have';
    const description = extractTextContent(g, 'description') || 'Goal description';
    const metric = extractTextContent(g, 'metric');
    return { priority, description, metric };
  });

  // Extract non-goals
  const nonGoalMatches = goalsMatch[1].match(/<nonGoal[^>]*>([\s\S]*?)<\/nonGoal>/g) || [];
  const nonGoals = nonGoalMatches.map((ng) => {
    const description = extractTextContent(ng, 'description') || 'Non-goal description';
    const reason = extractTextContent(ng, 'reason') || 'Reason not specified';
    return { description, reason };
  });

  // Extract success metrics
  const metricsMatch = goalsMatch[1].match(/<successMetrics>([\s\S]*?)<\/successMetrics>/);
  const metricMatches = metricsMatch ? metricsMatch[1].match(/<metric[^>]*>([\s\S]*?)<\/metric>/g) || [] : [];
  const metrics = metricMatches.map((m) => {
    const name = extractTextContent(m, 'name') || 'Metric';
    const target = extractTextContent(m, 'target') || 'TBD';
    const method = extractTextContent(m, 'measurementMethod') || 'TBD';
    const baseline = extractTextContent(m, 'baseline') || 'N/A';
    return { name, target, method, baseline };
  });

  return `### 2.3 Goals & Non-Goals

#### Goals
${goals.length > 0
    ? goals.map((g, i) => `${i + 1}. **${g.description}** _(${formatPriority(g.priority)})_${g.metric ? `\n   - Metric: ${g.metric}` : ''}`).join('\n')
    : '- No goals specified'}

#### Non-Goals
${nonGoals.length > 0
    ? nonGoals.map((ng, i) => `${i + 1}. ${ng.description}\n   - _Reason: ${ng.reason}_`).join('\n')
    : '- No non-goals specified'}

#### Success Metrics
${metrics.length > 0
    ? `| Metric | Target | Measurement | Baseline |
|--------|--------|-------------|----------|
${metrics.map((m) => `| ${m.name} | ${m.target} | ${m.method} | ${m.baseline} |`).join('\n')}`
    : '- No success metrics defined'}
`;
}

/**
 * Format User Personas subsection
 */
function formatPersonas(xml: string): string {
  const personasMatch = xml.match(/<personas>([\s\S]*?)<\/personas>/);
  if (!personasMatch) {
    return `### 2.4 User Personas

> User personas not available.
`;
  }

  const personaMatches = personasMatch[1].match(/<persona[^>]*>([\s\S]*?)<\/persona>/g) || [];

  if (personaMatches.length === 0) {
    return `### 2.4 User Personas

> No personas defined.
`;
  }

  const personas = personaMatches.map((p) => {
    const name = extractTextContent(p, 'name') || 'Unknown';
    const role = extractTextContent(p, 'role') || 'User';
    const demographicsMatch = p.match(/<demographics>([\s\S]*?)<\/demographics>/);
    const age = demographicsMatch ? extractTextContent(demographicsMatch[1], 'age') : '';
    const location = demographicsMatch ? extractTextContent(demographicsMatch[1], 'location') : '';
    const expertise = demographicsMatch ? extractTextContent(demographicsMatch[1], 'technicalExpertise') || 'intermediate' : 'intermediate';
    const needs = extractListItems(p, 'need');
    const painPoints = extractListItems(p, 'painPoint');
    const quotation = extractTextContent(p, 'quotation');

    return `#### ${name}
**Role:** ${role}
**Demographics:** ${[age, location].filter(Boolean).join(', ')} _(${expertise} technical skill)_

**Needs:**
${needs.length > 0 ? needs.map((n) => `- ${n}`).join('\n') : '- Not specified'}

**Pain Points:**
${painPoints.length > 0 ? painPoints.map((pp) => `- ${pp}`).join('\n') : '- Not specified'}

${quotation ? `> "${quotation}"` : ''}
`;
  });

  return `### 2.4 User Personas

${personas.join('\n---\n\n')}
`;
}

/**
 * Format Epic → Feature → Story Hierarchy subsection
 */
function formatEpicFeatureStoryHierarchy(xml: string): string {
  const epicsMatch = xml.match(/<epics>([\s\S]*?)<\/epics>/);
  if (!epicsMatch) {
    return `### 2.5 Epic → Feature → Story Breakdown

> User stories hierarchy not available.
`;
  }

  const epicMatches = epicsMatch[1].match(/<epic[^>]*>([\s\S]*?)<\/epic>/g) || [];

  if (epicMatches.length === 0) {
    return `### 2.5 Epic → Feature → Story Breakdown

> No epics defined.
`;
  }

  const epics = epicMatches.map((epicXml) => {
    const epicId = epicXml.match(/id="([^"]+)"/)?.[1] || 'E0';
    const epicName = epicXml.match(/name="([^"]+)"/)?.[1] || 'Unnamed Epic';
    const epicPriority = epicXml.match(/priority="([^"]+)"/)?.[1] || 'high';
    const businessObjective = extractTextContent(epicXml, 'businessObjective') || '';
    const estimatedDuration = extractTextContent(epicXml, 'estimatedDuration');

    // Parse features
    const featuresMatch = epicXml.match(/<features>([\s\S]*?)<\/features>/);
    const featureMatches = featuresMatch ? featuresMatch[1].match(/<feature[^>]*>([\s\S]*?)<\/feature>/g) || [] : [];

    const features = featureMatches.map((featureXml) => {
      const featureId = featureXml.match(/id="([^"]+)"/)?.[1] || 'F0';
      const featureName = featureXml.match(/name="([^"]+)"/)?.[1] || 'Unnamed Feature';
      const complexity = featureXml.match(/estimatedComplexity="([^"]+)"/)?.[1] || 'medium';
      const businessValue = extractTextContent(featureXml, 'businessValue') || '';

      // Parse stories
      const storiesMatch = featureXml.match(/<stories>([\s\S]*?)<\/stories>/);
      const storyMatches = storiesMatch ? storiesMatch[1].match(/<story[^>]*>([\s\S]*?)<\/story>/g) || [] : [];

      const stories = storyMatches.map((storyXml) => {
        const storyId = storyXml.match(/id="([^"]+)"/)?.[1] || 'US-000';
        const title = extractTextContent(storyXml, 'title') || 'Untitled Story';
        const asA = extractTextContent(storyXml, 'asA') || 'user';
        const iWant = extractTextContent(storyXml, 'iWant') || '';
        const soThat = extractTextContent(storyXml, 'soThat') || '';
        const priority = storyXml.match(/priority="([^"]+)"/)?.[1] || 'medium';
        const effort = storyXml.match(/estimatedEffort="([^"]+)"/)?.[1] || 'medium';
        const relatedEntities = extractListItems(storyXml, 'relatedEntity') || extractListItems(storyXml, 'entity');
        const relatedEndpoints = extractListItems(storyXml, 'relatedEndpoint') || extractListItems(storyXml, 'endpoint');

        return { storyId, title, asA, iWant, soThat, priority, effort, relatedEntities, relatedEndpoints };
      });

      return { featureId, featureName, complexity, businessValue, stories };
    });

    return { epicId, epicName, epicPriority, businessObjective, estimatedDuration, features };
  });

  const output = epics.map((epic) => {
    const featuresOutput = epic.features.map((feature) => {
      const storiesOutput = feature.stories.map((story) => {
        return `###### ${story.storyId}: ${story.title}
**As a** ${story.asA}, **I want** ${story.iWant}, **so that** ${story.soThat}

| Priority | Effort | Related Entities | Related Endpoints |
|----------|--------|------------------|-------------------|
| ${formatPriority(story.priority)} | ${story.effort} | ${story.relatedEntities.join(', ') || 'N/A'} | ${story.relatedEndpoints.join(', ') || 'N/A'} |
`;
      }).join('\n');

      return `##### Feature: ${feature.featureName} _(Complexity: ${feature.complexity})_
**ID:** ${feature.featureId}
${feature.businessValue ? `**Business Value:** ${feature.businessValue}` : ''}

**User Stories:**
${storiesOutput || '> No stories defined'}
`;
    }).join('\n---\n\n');

    return `#### Epic: ${epic.epicName} _(${formatPriority(epic.epicPriority)})_
**ID:** ${epic.epicId}
**Business Objective:** ${epic.businessObjective || 'Not specified'}
${epic.estimatedDuration ? `**Estimated Duration:** ${epic.estimatedDuration}` : ''}

${featuresOutput || '> No features defined'}
`;
  }).join('\n\n---\n\n');

  return `### 2.5 Epic → Feature → Story Breakdown

${output}
`;
}

/**
 * Format Functional Requirements Summary subsection
 */
function formatFunctionalRequirementsSummary(xml: string): string {
  // Count total functional requirements
  const reqMatches = xml.match(/<requirement[^>]*>([\s\S]*?)<\/requirement>/g) || [];
  const totalReqs = reqMatches.length;

  if (totalReqs === 0) {
    return `### 2.6 Functional Requirements Summary

> No functional requirements defined.
`;
  }

  // Sample some requirements
  const sampleReqs = reqMatches.slice(0, 5).map((r) => {
    const id = r.match(/id="([^"]+)"/)?.[1] || 'FR-X';
    const description = extractTextContent(r, 'description') || 'Requirement';
    const given = extractTextContent(r, 'given') || '';
    const when = extractTextContent(r, 'when') || '';
    const then = extractTextContent(r, 'then') || '';
    return { id, description, given, when, then };
  });

  return `### 2.6 Functional Requirements Summary

**Total Requirements:** ${totalReqs}

#### Sample Requirements (Given/When/Then Format)

${sampleReqs.map((r) => `**${r.id}: ${r.description}**
- **Given:** ${r.given || 'N/A'}
- **When:** ${r.when || 'N/A'}
- **Then:** ${r.then || 'N/A'}
`).join('\n')}

${totalReqs > 5 ? `> _...and ${totalReqs - 5} more requirements_` : ''}
`;
}

/**
 * Format Edge Cases Summary subsection
 */
function formatEdgeCasesSummary(xml: string): string {
  const edgeCaseMatches = xml.match(/<edgeCase[^>]*>([\s\S]*?)<\/edgeCase>/g) || [];
  const totalEdgeCases = edgeCaseMatches.length;

  if (totalEdgeCases === 0) {
    return `### 2.7 Edge Cases Summary

> No edge cases defined.
`;
  }

  // Categorize by severity
  const critical = edgeCaseMatches.filter((ec) => ec.includes('severity="critical"')).length;
  const major = edgeCaseMatches.filter((ec) => ec.includes('severity="major"')).length;
  const minor = edgeCaseMatches.filter((ec) => ec.includes('severity="minor"')).length;

  // Sample some edge cases
  const sampleCases = edgeCaseMatches.slice(0, 5).map((ec) => {
    const severity = ec.match(/severity="([^"]+)"/)?.[1] || 'major';
    const scenario = extractTextContent(ec, 'scenario') || 'Edge case';
    const expected = extractTextContent(ec, 'expectedBehavior') || '';
    return { severity, scenario, expected };
  });

  return `### 2.7 Edge Cases Summary

**Total Edge Cases:** ${totalEdgeCases}

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${critical} |
| 🟠 Major | ${major} |
| 🟡 Minor | ${minor} |

#### Sample Edge Cases

${sampleCases.map((ec) => `- **[${ec.severity.toUpperCase()}]** ${ec.scenario}
  - _Expected: ${ec.expected || 'Not specified'}_
`).join('\n')}

${totalEdgeCases > 5 ? `> _...and ${totalEdgeCases - 5} more edge cases_` : ''}
`;
}

/**
 * Format Acceptance Criteria Summary subsection
 */
function formatAcceptanceCriteriaSummary(xml: string): string {
  const criteriaMatches = xml.match(/<criterion[^>]*>([\s\S]*?)<\/criterion>/g) || [];
  const totalCriteria = criteriaMatches.length;

  if (totalCriteria === 0) {
    return `### 2.8 Acceptance Criteria Summary

> No acceptance criteria defined.
`;
  }

  // Categorize by type
  const functional = criteriaMatches.filter((c) => c.includes('type="functional"')).length;
  const ui = criteriaMatches.filter((c) => c.includes('type="ui"')).length;
  const security = criteriaMatches.filter((c) => c.includes('type="security"')).length;
  const performance = criteriaMatches.filter((c) => c.includes('type="performance"')).length;
  const accessibility = criteriaMatches.filter((c) => c.includes('type="accessibility"')).length;

  return `### 2.8 Acceptance Criteria Summary

**Total Criteria:** ${totalCriteria}

| Type | Count |
|------|-------|
| Functional | ${functional} |
| UI | ${ui} |
| Security | ${security} |
| Performance | ${performance} |
| Accessibility | ${accessibility} |

> Detailed acceptance criteria are included within each user story above.
`;
}

// ============ User Stories Helper Functions ============

/**
 * Extract text content from XML tag
 */
function extractTextContent(xml: string, tagName: string): string | undefined {
  // Try CDATA first
  const cdataMatch = xml.match(new RegExp(`<${tagName}><!\\[CDATA\\[([\\s\\S]*?)\\]\\]></${tagName}>`));
  if (cdataMatch) return cdataMatch[1]?.trim();

  // Try regular content
  const match = xml.match(new RegExp(`<${tagName}>([^<]*)</${tagName}>`));
  return match?.[1]?.trim();
}

/**
 * Extract list items from XML
 */
function extractListItems(xml: string, itemTagName: string): string[] {
  const items: string[] = [];
  const regex = new RegExp(`<${itemTagName}[^>]*>([^<]*)</${itemTagName}>`, 'g');
  let match;

  while ((match = regex.exec(xml)) !== null) {
    const text = match[1]?.trim();
    if (text) {
      items.push(text);
    }
  }

  return items;
}

/**
 * Format priority for display
 */
function formatPriority(priority: string): string {
  const priorityMap: Record<string, string> = {
    critical: '🔴 Critical',
    must_have: '🔴 Must Have',
    high: '🟠 High',
    should_have: '🟠 Should Have',
    medium: '🟡 Medium',
    nice_to_have: '🟡 Nice to Have',
    low: '🟢 Low',
    later: '⚪ Later',
  };
  return priorityMap[priority.toLowerCase()] || priority;
}

/**
 * Build Database Schema section
 */
function buildDatabaseSection(databaseXml: string): string {
  if (!databaseXml) {
    return `## 3. Database Schema

> Database schema not generated.

---
`;
  }

  return `## 3. Database Schema

### 3.1 Schema Definition (XML)

\`\`\`xml
${databaseXml}
\`\`\`

### 3.2 Entity Summary

${extractEntitySummary(databaseXml)}

### 3.3 Relationships

${extractRelationshipSummary(databaseXml)}

---
`;
}

/**
 * Build API Documentation section
 */
function buildAPISection(backendXml: string): string {
  if (!backendXml) {
    return `## 4. API Documentation

> API documentation not generated.

---
`;
  }

  return `## 4. API Documentation

### 4.1 Architecture (XML)

\`\`\`xml
${backendXml}
\`\`\`

### 4.2 Endpoint Summary

${extractEndpointSummary(backendXml)}

### 4.3 Authentication

${extractAuthSummary(backendXml)}

---
`;
}

/**
 * Build Security section
 */
function buildSecuritySection(securityXml: string): string {
  if (!securityXml) {
    return `## 5. Security Recommendations

> Security recommendations not generated.

---
`;
  }

  return `## 5. Security Recommendations

### 5.1 Security Configuration (XML)

\`\`\`xml
${securityXml}
\`\`\`

### 5.2 OWASP Coverage

${extractOwaspSummary(securityXml)}

### 5.3 Data Protection

${extractDataProtectionSummary(securityXml)}

---
`;
}

/**
 * Build Testing section
 */
function buildTestingSection(testingXml: string): string {
  if (!testingXml) {
    return `## 6. Testing Strategy

> Testing strategy not generated.

---
`;
  }

  return `## 6. Testing Strategy

### 6.1 Testing Configuration (XML)

\`\`\`xml
${testingXml}
\`\`\`

### 6.2 Test Suites

${extractTestSuitesSummary(testingXml)}

---
`;
}

/**
 * Build DevOps section
 */
function buildDevOpsSection(devopsXml: string): string {
  if (!devopsXml) {
    return `## 7. DevOps Configuration

> DevOps configuration not generated.

---
`;
  }

  return `## 7. DevOps Configuration

### 7.1 DevOps Configuration (XML)

\`\`\`xml
${devopsXml}
\`\`\`

### 7.2 Services

${extractServicesSummary(devopsXml)}

### 7.3 Hosting Recommendations

${extractHostingSummary(devopsXml)}

---
`;
}

/**
 * Build Tech Stack section
 */
function buildTechStackSection(): string {
  return `## 8. Tech Stack Summary

| Layer | Technology |
|-------|------------|
| **Backend** | Node.js + Express |
| **Database** | PostgreSQL |
| **ORM** | Prisma |
| **Frontend** | React |
| **API** | REST + GraphQL |
| **Auth** | JWT |
| **Containerization** | Docker |
| **CI/CD** | GitHub Actions |

---
`;
}

/**
 * Build Validation Report section
 */
function buildValidationReportSection(
  scores: { completeness: number; consistency: number; security: number; implementability: number; overall: number },
  qaIterations: number
): string {
  return `## 9. Validation Report

| Metric | Score |
|--------|-------|
| Completeness | ${scores.completeness}/100 |
| Consistency | ${scores.consistency}/100 |
| Security | ${scores.security}/100 |
| Implementability | ${scores.implementability}/100 |
| **Overall** | **${scores.overall}/100** |

- **QA Iterations:** ${qaIterations}
- **Approval Status:** ${scores.overall >= 70 ? '✅ Approved' : '⚠️ Needs Review'}
`;
}

// ============ Helper Functions ============

function extractValidationScores(validationXml: string): {
  completeness: number;
  consistency: number;
  security: number;
  implementability: number;
  overall: number;
} {
  const defaultScores = { completeness: 0, consistency: 0, security: 0, implementability: 0, overall: 0 };

  if (!validationXml) return defaultScores;

  const completenessMatch = validationXml.match(/<completeness\s+score="(\d+)"/);
  const consistencyMatch = validationXml.match(/<consistency\s+score="(\d+)"/);
  const securityMatch = validationXml.match(/<security\s+score="(\d+)"/);
  const implementabilityMatch = validationXml.match(/<implementability\s+score="(\d+)"/);
  const overallMatch = validationXml.match(/<overall\s+score="(\d+)"/);

  return {
    completeness: completenessMatch ? parseInt(completenessMatch[1], 10) : 0,
    consistency: consistencyMatch ? parseInt(consistencyMatch[1], 10) : 0,
    security: securityMatch ? parseInt(securityMatch[1], 10) : 0,
    implementability: implementabilityMatch ? parseInt(implementabilityMatch[1], 10) : 0,
    overall: overallMatch ? parseInt(overallMatch[1], 10) : 0,
  };
}

function extractEntitySummary(xml: string): string {
  const entities = xml.match(/<entity\s+name="([^"]+)"/g) || [];
  if (entities.length === 0) return 'No entities defined.';

  return entities
    .map((e) => {
      const name = e.match(/name="([^"]+)"/)?.[1] || 'Unknown';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractRelationshipSummary(xml: string): string {
  const relations = xml.match(/<relation[^>]+\/>/g) || [];
  if (relations.length === 0) return 'No relationships defined.';

  return relations
    .map((r) => {
      const from = r.match(/from="([^"]+)"/)?.[1] || '';
      const to = r.match(/to="([^"]+)"/)?.[1] || '';
      const type = r.match(/type="([^"]+)"/)?.[1] || '';
      return `- ${from} → ${to} (${type})`;
    })
    .join('\n');
}

function extractEndpointSummary(xml: string): string {
  const resources = xml.match(/<resource\s+name="([^"]+)"/g) || [];
  if (resources.length === 0) return 'No endpoints defined.';

  const endpoints = xml.match(/<endpoint[^>]+method="([^"]+)"[^>]+path="([^"]+)"/g) || [];

  return `| Method | Path |
|--------|------|
${endpoints
    .slice(0, 15)
    .map((e) => {
      const method = e.match(/method="([^"]+)"/)?.[1] || '';
      const path = e.match(/path="([^"]+)"/)?.[1] || '';
      return `| ${method} | ${path} |`;
    })
    .join('\n')}${endpoints.length > 15 ? `\n\n*...and ${endpoints.length - 15} more endpoints*` : ''}`;
}

function extractAuthSummary(xml: string): string {
  const strategy = xml.match(/<strategy>([^<]+)<\/strategy>/)?.[1] || 'JWT';
  const accessExpiry = xml.match(/<accessTokenExpiry>([^<]+)<\/accessTokenExpiry>/)?.[1] || '15m';
  const refreshExpiry = xml.match(/<refreshTokenExpiry>([^<]+)<\/refreshTokenExpiry>/)?.[1] || '7d';

  return `- **Strategy:** ${strategy}
- **Access Token Expiry:** ${accessExpiry}
- **Refresh Token Expiry:** ${refreshExpiry}`;
}

function extractOwaspSummary(xml: string): string {
  const risks = xml.match(/<risk\s+name="([^"]+)"/g) || [];
  if (risks.length === 0) return 'OWASP coverage not specified.';

  return risks
    .map((r) => {
      const name = r.match(/name="([^"]+)"/)?.[1] || '';
      return `- ✅ ${name}`;
    })
    .join('\n');
}

function extractDataProtectionSummary(xml: string): string {
  const atRest = xml.match(/atRest="([^"]+)"/)?.[1] || 'true';
  const inTransit = xml.match(/inTransit="([^"]+)"/)?.[1] || 'true';

  return `- **Encryption at Rest:** ${atRest === 'true' ? 'Yes' : 'No'}
- **Encryption in Transit:** ${inTransit === 'true' ? 'Yes (TLS)' : 'No'}`;
}

function extractTestSuitesSummary(xml: string): string {
  const suites = xml.match(/<suite\s+name="([^"]+)"/g) || [];
  const resourceSuites = xml.match(/<suite\s+resource="([^"]+)"/g) || [];

  const allSuites = [
    ...suites.map((s) => s.match(/name="([^"]+)"/)?.[1] || ''),
    ...resourceSuites.map((s) => `${s.match(/resource="([^"]+)"/)?.[1] || ''} API Tests`),
  ].filter(Boolean);

  if (allSuites.length === 0) return 'No test suites defined.';

  return allSuites.map((s) => `- ${s}`).join('\n');
}

function extractServicesSummary(xml: string): string {
  const services = xml.match(/<service\s+name="([^"]+)"/g) || [];
  if (services.length === 0) return 'No services defined.';

  return services
    .map((s) => {
      const name = s.match(/name="([^"]+)"/)?.[1] || '';
      return `- **${name}**`;
    })
    .join('\n');
}

function extractHostingSummary(xml: string): string {
  const recommendations = xml.match(/<recommendation\s+provider="([^"]+)"[^>]*>/g) || [];
  if (recommendations.length === 0) return 'No hosting recommendations.';

  return recommendations
    .map((r) => {
      const provider = r.match(/provider="([^"]+)"/)?.[1] || '';
      return `- **${provider}**`;
    })
    .join('\n');
}

export default synthesizePRD;
