/**
 * PostgreSQL PRD Repository
 *
 * Repository for managing PRD (Product Requirements Document) entities
 * generated by the Technical Architecture Pipeline.
 */

import { v4 as uuidv4 } from 'uuid';
import { getKnex } from '../../../config/knex';
import {
  IPRDRepository,
  PRDData,
  PRDSummary,
  PRDListResult,
  CreatePRDDTO,
  UpdatePRDDTO,
  PRDPipelineType,
  PRDDetailLevel,
} from '../interfaces';

export class PostgresPRDRepository implements IPRDRepository {
  private get db() {
    return getKnex();
  }

  /**
   * Map database row to PRD summary (for list views)
   */
  private mapRowToSummary(row: any): PRDSummary {
    return {
      id: row.id,
      sourceUrl: row.source_url,
      pipelineType: row.pipeline_type as PRDPipelineType,
      detailLevel: row.detail_level as PRDDetailLevel,
      validationScore: row.validation_score,
      qaApproved: row.qa_approved || false,
      createdAt: row.created_at,
    };
  }

  /**
   * Map database row to full PRD data
   */
  private mapRowToPRD(row: any): PRDData {
    return {
      id: row.id,
      userId: row.user_id,
      sourceUrl: row.source_url,
      pipelineType: row.pipeline_type as PRDPipelineType,
      detailLevel: row.detail_level as PRDDetailLevel,
      visualAnalysis: row.visual_analysis,
      databaseSchema: row.database_schema,
      backendArchitecture: row.backend_architecture,
      securityRecommendations: row.security_recommendations,
      testingStrategy: row.testing_strategy,
      devopsConfig: row.devops_config,
      validationResult: row.validation_result,
      validationScore: row.validation_score,
      qaReview: row.qa_review,
      qaIterations: row.qa_iterations || 0,
      qaApproved: row.qa_approved || false,
      prdMarkdown: row.prd_markdown,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    };
  }

  /**
   * Find PRD by ID
   */
  async findById(id: string): Promise<PRDData | null> {
    const row = await this.db('prds').where({ id }).first();

    if (!row) {
      return null;
    }

    return this.mapRowToPRD(row);
  }

  /**
   * Find PRDs by user ID with pagination
   */
  async findByUserId(userId: string, page = 1, limit = 10): Promise<PRDListResult> {
    const offset = (page - 1) * limit;

    const [countResult, rows] = await Promise.all([
      this.db('prds').where({ user_id: userId }).count('id as count').first(),
      this.db('prds')
        .select(
          'id',
          'source_url',
          'pipeline_type',
          'detail_level',
          'validation_score',
          'qa_approved',
          'created_at'
        )
        .where({ user_id: userId })
        .orderBy('created_at', 'desc')
        .limit(limit)
        .offset(offset),
    ]);

    const total = parseInt(String(countResult?.count || 0), 10);

    return {
      prds: rows.map((row: any) => this.mapRowToSummary(row)),
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
        hasMore: page * limit < total,
      },
    };
  }

  /**
   * Find PRDs by source URL
   */
  async findByUrl(url: string): Promise<PRDData[]> {
    const rows = await this.db('prds')
      .where({ source_url: url })
      .orderBy('created_at', 'desc');

    return rows.map((row: any) => this.mapRowToPRD(row));
  }

  /**
   * Create a new PRD
   */
  async create(data: CreatePRDDTO): Promise<PRDData> {
    const id = uuidv4();

    const [row] = await this.db('prds')
      .insert({
        id,
        user_id: data.userId || null,
        source_url: data.sourceUrl,
        pipeline_type: data.pipelineType,
        detail_level: data.detailLevel,
        visual_analysis: data.visualAnalysis ? JSON.stringify(data.visualAnalysis) : null,
        database_schema: data.databaseSchema || null,
        backend_architecture: data.backendArchitecture || null,
        security_recommendations: data.securityRecommendations || null,
        testing_strategy: data.testingStrategy || null,
        devops_config: data.devopsConfig || null,
        validation_result: data.validationResult || null,
        validation_score: data.validationScore || null,
        qa_review: data.qaReview || null,
        qa_iterations: data.qaIterations || 0,
        qa_approved: data.qaApproved || false,
        prd_markdown: data.prdMarkdown,
        created_at: this.db.fn.now(),
        updated_at: this.db.fn.now(),
      })
      .returning('*');

    return this.mapRowToPRD(row);
  }

  /**
   * Update an existing PRD
   */
  async update(id: string, data: UpdatePRDDTO): Promise<PRDData | null> {
    const updateData: Record<string, any> = {};

    if (data.visualAnalysis !== undefined) {
      updateData.visual_analysis = JSON.stringify(data.visualAnalysis);
    }
    if (data.databaseSchema !== undefined) {
      updateData.database_schema = data.databaseSchema;
    }
    if (data.backendArchitecture !== undefined) {
      updateData.backend_architecture = data.backendArchitecture;
    }
    if (data.securityRecommendations !== undefined) {
      updateData.security_recommendations = data.securityRecommendations;
    }
    if (data.testingStrategy !== undefined) {
      updateData.testing_strategy = data.testingStrategy;
    }
    if (data.devopsConfig !== undefined) {
      updateData.devops_config = data.devopsConfig;
    }
    if (data.validationResult !== undefined) {
      updateData.validation_result = data.validationResult;
    }
    if (data.validationScore !== undefined) {
      updateData.validation_score = data.validationScore;
    }
    if (data.qaReview !== undefined) {
      updateData.qa_review = data.qaReview;
    }
    if (data.qaIterations !== undefined) {
      updateData.qa_iterations = data.qaIterations;
    }
    if (data.qaApproved !== undefined) {
      updateData.qa_approved = data.qaApproved;
    }
    if (data.prdMarkdown !== undefined) {
      updateData.prd_markdown = data.prdMarkdown;
    }

    if (Object.keys(updateData).length === 0) {
      return this.findById(id);
    }

    updateData.updated_at = this.db.fn.now();

    const [row] = await this.db('prds')
      .where({ id })
      .update(updateData)
      .returning('*');

    if (!row) {
      return null;
    }

    return this.mapRowToPRD(row);
  }

  /**
   * Delete a PRD
   */
  async delete(id: string): Promise<boolean> {
    const deletedCount = await this.db('prds').where({ id }).delete();
    return deletedCount > 0;
  }

  /**
   * Get only the markdown content of a PRD (for download)
   */
  async getMarkdown(id: string): Promise<string | null> {
    const row = await this.db('prds')
      .select('prd_markdown')
      .where({ id })
      .first();

    return row?.prd_markdown || null;
  }
}
